import { ProjectCardDTO } from '@/entities/project';

export const projectsListMock: ProjectCardDTO[] = [
  {
    id: '1',
    title: 'Project One',
    photo:
      'https://avatars.mds.yandex.net/i?id=4dac695074265c0e107f58e9db7e4cfc_l-10871821-images-thumbs&n=13',
    shortDescription: 'Short description of project one.',
    author: 'Author One',
    rating: 2.5,
    commentsCount: 10,
    viewsCount: 100,
  },
  {
    id: '2',
    title: 'Project Two',
    photo:
      'https://cdn.ananasposter.ru/image/cache/catalog/poster/pos23/23/68584-1000x830.jpg',
    shortDescription:
      'ShОчень интересное краткое описание прекрасного проекта, чтобы все знали какой он классный Очень интересное краткое описание прекрасного проекта, чтобы все знали какой он классный ОчеОчень интересное краткое описание прекрасного проекта, чтобы все знали какой он классный нь интересное краткое описание прекрасного проекта, чтобы все знали какой он классный ort description of project two.',
    author: 'Author Two',
    rating: 3.8,
    commentsCount: 8,
    viewsCount: 150,
  },
  {
    id: '3',
    title: 'Project Three',
    photo:
      'https://nypost.com/wp-content/uploads/sites/2/2022/08/Ryan-Gosling-84.jpg',
    shortDescription:
      'Очень интересное краткое описание прекрасного проекта, чтобы все знали какой он классный ',
    author: 'Author Three',
    rating: 4.2,
    commentsCount: 5,
    viewsCount: 200,
  },
  {
    id: '4',
    title: 'Project Four',
    photo:
      'https://avatars.mds.yandex.net/get-mpic/5214322/img_id3428486128927288209.jpeg/orig',
    shortDescription: 'Short description of project four.',
    author: 'Author Four',
    rating: 4.777,
    commentsCount: 12,
    viewsCount: 250,
  },
  {
    id: '5',
    title: 'Project Five',
    photo: 'photo5.jpg',
    shortDescription: 'Short description of project five.',
    author: 'Author Five',
    rating: 3.9,
    commentsCount: 6,
    viewsCount: 120,
  },
  {
    id: '6',
    title: 'Project Six',
    photo: 'photo6.jpg',
    shortDescription:
      'Очень интересное краткое описание прекрасного проекта, чтобы все знали какой он классный .',
    author: 'Author Six',
    rating: 4.7,
    commentsCount: 9,
    viewsCount: 300,
  },
  {
    id: '7',
    title: 'Project Seven',
    photo: 'photo7.jpg',
    shortDescription: 'Short description of project seven.',
    author: 'Author Seven',
    rating: 4.3,
    commentsCount: 7,
    viewsCount: 180,
  },
  {
    id: '8',
    title: 'Project Eight',
    photo: 'photo8.jpg',
    shortDescription:
      'Очень интересное краткое описание прекрасного проекта, чтобы все знали какой он классный ',
    author: 'Author Eight',
    rating: 4.1,
    commentsCount: 11,
    viewsCount: 220,
  },
  {
    id: '9',
    title: 'Project Nine',
    photo: 'photo9.jpg',
    shortDescription: 'Short description of project nine.',
    author: 'Author Nine',
    rating: 4.6,
    commentsCount: 13,
    viewsCount: 270,
  },
  {
    id: '10',
    title: 'Project Ten',
    photo: 'photo10.jpg',
    shortDescription: 'Short description of project ten.',
    author: 'Author Ten',
    rating: 4.4,
    commentsCount: 14,
    viewsCount: 320,
  },
  {
    id: '11',
    title: 'Project Eleven',
    photo: 'photo11.jpg',
    shortDescription: 'Short description of project eleven.',
    author: 'Author Eleven',
    rating: 4.0,
    commentsCount: 8,
    viewsCount: 140,
  },
  {
    id: '12',
    title: 'Project Twelve',
    photo: 'photo12.jpg',
    shortDescription: 'Short description of project twelve.',
    author: 'Author Twelve',
    rating: 4.9,
    commentsCount: 15,
    viewsCount: 350,
  },
];
